# Generated by Django 3.2.9 on 2022-05-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-fecha']},
        ),
    ]
